name: Frontend CI
on: 
  pull_request:
    paths:
      - 'node/**'

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      working-directory: node/
      run: |
        npm install
    - name: Run Frontend Tests
      working-directory: node/
      run: |
        ./runtests.sh