name: api CI
on: 
  pull_request:
    paths:
      - 'go/**'

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - name: setup git
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends git
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: Install dependencies
      working-directory: go/
      run: |
        go mod download
        go mod verify
    - name: Build
      working-directory: go/
      run: |
        go build ./func/fib.go
        ./fib
    - name: Run api Tests
      working-directory: go/
      run: |
        ./runtests.sh