on: push 

jobs:
  gcloudac:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install gcloud SDK
      run: |
        sudo apt-get update && sudo apt-get install google-cloud-sdk
    - name: Activate Service Account 
      env: 
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      run: |
        echo "$GCLOUD_AUTH" > "$HOME"/gcloud.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud.json $*
