name: Labeler

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Labeler
      uses: estrada9166/labeler@v1
      with:
        GITHUB_TOKEN: "${{ secrets.TOKEN }}"
        CONFIG_PATH: labeler-config.yml
