name: Labeler

on: pull_request


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Labeler
      uses: docker://decathlon/pull-request-labeler-action:2.0.0
      with:
        GITHUB_TOKEN: "${{ secrets.TOKEN }}"
        CONFIG_PATH: config.yml
