name: Python application

on: 
  push:
    paths:
    - 'python/**'
    - 'python_2/**'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies on python
      working-directory: python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest in python
      working-directory: python
      run: |
        chmod +x ./python/test.sh
        ./test.sh
    - name: Install dependencies in python_2
      working-directory: python_2
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest in python_2
      working-directory: python_2
      run: |
        chmod +x test.sh
        ./test.sh