name: Python application

on: 
  push:
    paths:
    - 'python_2/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python_2/requirements.txt
    - name: Test with pytest
      run: |
        chmod +x ./python_2/test.sh
        ./python_2/test.sh
