name: Python application

on: 
  push:
    paths:
    - 'python/**'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Test with pytest
      run: |
        chmod +x ./python/test.sh
        ./python/test.sh
